---
title: "MS 2"
author: "Prabidhik KC"
date: "2/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The History of the Olympic Games

The project "The History of the Olympic Games" by Olly Gill, a sophomore student who took the GOV 1005 class on Fall 2019 is a beautifully arranged project which shows the different trends in the Olympic games over years. The project is based on big data where he uses large dataset. I really liked the project as it is beautifully categorized into different sections: Olympic Characteristics which has further four sections which includes Trends, Winter Games, Summer Games, Location; Athletic characteristics which includes further 4 sub sections; statistical analysis where she analyses the data and show the findings. This project can be easily understood by any people. This is a great project with detailed analysis. I think the project would have been even better if we could get more information on dragging the cursor over the particular data in the three line plots which appear frequently in the project. I think it would also have been great if she had color code the data of gold, silver, and bronze with gold, silver, and bronze color rather than red, green in the summer and winter game sections.



Harvard Dining

The project "Harvard Dining" by Neil Khurana, who took GOV 1005 in Spring 2019 is a interesting project especially for the Harvard students, staff, and anyone associated with Harvard. He categorizes the project into different section making the project user friendly. I particularly like the Calendar section where he makes the drop down list for meal selection and the formatting of date input. He shows the trend with bar graphs on frequently served menu items. This project, I found to be very effective. I think it would have been better if he managed the width of the bar graphs to appropriate size in order to make the graph look better and effective. It would have been better if he could color code the menu item by different colors instead of using just red, and also it would have been better use the different saturation of the color to show the frequency served.